package formularios;

import java.sql.DriverManager;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;


/**
 *
 * @author oscar
 */
public final class jf_productos extends javax.swing.JFrame {
    public int anterior = 0;
    private Connection conexion;
    private Statement st;
    private ResultSet rs;
    /**
     * Creates new form jf_productos
     */
    public jf_productos() {
        initComponents();
        this.Conectar();
        jp_datos.setEnabled(true);
        jb_nuevo.setEnabled(true);
        jb_editar.setEnabled(true);
        jb_borrar.setEnabled(true);
        jb_guardar.setEnabled(false);
        jb_cancelar.setEnabled(false);
        habilitarjtf(false);
        habilitarcontroles(true);
        
    }
    
    public void habilitarjtf(boolean x){
        jtf_id_producto.setEnabled(x);
        jtf_nombre_producto.setEnabled(x);           
        jtf_marca_producto.setEnabled(x);
        jtf_precio_producto.setEnabled(x);
        jtf_existencia_producto.setEnabled(x);
    }
    
    public void habilitarcontroles(boolean y){
        jb_primero.setEnabled(y);
        jb_anterior.setEnabled(y);
        jb_siguiente.setEnabled(y);
        jb_ultimo.setEnabled(y);
    }
    public void limpiarjtf(){
        this.jtf_id_producto.setText("");             
        this.jtf_nombre_producto.setText("");
        this.jtf_marca_producto.setText("");
        this.jtf_precio_producto.setText("");
        this.jtf_existencia_producto.setText("");
    }
    public void Conectar(){
         try{ 
            conexion=DriverManager.getConnection("jdbc:mysql://localhost:3306/ferreteria","root","");                     
            st=conexion.createStatement(); 

            rs=st.executeQuery("Select * from productos");             

            rs.next(); 

            this.jtf_id_producto.setText(rs.getString("id_producto"));                         
            this.jtf_nombre_producto.setText(rs.getString("nombre_producto"));             
            this.jtf_marca_producto.setText(rs.getString("marca_producto"));
            this.jtf_precio_producto.setText(rs.getString("precio_producto"));
            this.jtf_existencia_producto.setText(rs.getString("existencia_producto"));

        }catch(SQLException err){ 
            JOptionPane.showMessageDialog(null,"Error " +err.getMessage()); 
        } 

    } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jb_guardar1 = new javax.swing.JButton();
        jp_datos = new javax.swing.JPanel();
        jtf_nombre_producto = new javax.swing.JTextField();
        jtf_precio_producto = new javax.swing.JTextField();
        jtf_existencia_producto = new javax.swing.JTextField();
        jtf_id_producto = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jtf_marca_producto = new javax.swing.JTextField();
        jp_controlesmovimiento = new javax.swing.JPanel();
        jb_ultimo = new javax.swing.JButton();
        jb_primero = new javax.swing.JButton();
        jb_anterior = new javax.swing.JButton();
        jb_siguiente = new javax.swing.JButton();
        jp_controles = new javax.swing.JPanel();
        jb_cancelar = new javax.swing.JButton();
        jb_nuevo = new javax.swing.JButton();
        jb_editar = new javax.swing.JButton();
        jb_guardar = new javax.swing.JButton();
        jb_borrar = new javax.swing.JButton();

        jb_guardar1.setText("Guardar");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jp_datos.setBackground(new java.awt.Color(0, 102, 204));
        jp_datos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jp_datos.add(jtf_nombre_producto, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 130, -1));
        jp_datos.add(jtf_precio_producto, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 130, -1));
        jp_datos.add(jtf_existencia_producto, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, 130, -1));
        jp_datos.add(jtf_id_producto, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 130, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Marca");
        jp_datos.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre");
        jp_datos.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Precio");
        jp_datos.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Existencia");
        jp_datos.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("ID");
        jp_datos.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, -1, 20));
        jp_datos.add(jtf_marca_producto, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 130, -1));

        jp_controlesmovimiento.setBackground(new java.awt.Color(0, 102, 204));
        jp_controlesmovimiento.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jb_ultimo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jb_ultimo.setText(">|");
        jb_ultimo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_ultimoMouseClicked(evt);
            }
        });
        jp_controlesmovimiento.add(jb_ultimo, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 50, -1));

        jb_primero.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jb_primero.setText("|<");
        jb_primero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_primeroMouseClicked(evt);
            }
        });
        jp_controlesmovimiento.add(jb_primero, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 50, -1));

        jb_anterior.setBackground(new java.awt.Color(204, 204, 204));
        jb_anterior.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jb_anterior.setText("<<");
        jb_anterior.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_anteriorMouseClicked(evt);
            }
        });
        jb_anterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_anteriorActionPerformed(evt);
            }
        });
        jp_controlesmovimiento.add(jb_anterior, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 50, -1));

        jb_siguiente.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jb_siguiente.setText(">>");
        jb_siguiente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_siguienteMouseClicked(evt);
            }
        });
        jp_controlesmovimiento.add(jb_siguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 50, -1));

        jp_controles.setBackground(new java.awt.Color(0, 102, 204));
        jp_controles.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jb_cancelar.setText("Cancelar");
        jb_cancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_cancelarMouseClicked(evt);
            }
        });
        jb_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_cancelarActionPerformed(evt);
            }
        });
        jp_controles.add(jb_cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, -1, -1));

        jb_nuevo.setText("Nuevo");
        jb_nuevo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_nuevoMouseClicked(evt);
            }
        });
        jp_controles.add(jb_nuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 70, -1));

        jb_editar.setText("Editar");
        jb_editar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_editarMouseClicked(evt);
            }
        });
        jp_controles.add(jb_editar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 60, -1));

        jb_guardar.setText("Guardar");
        jb_guardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_guardarMouseClicked(evt);
            }
        });
        jp_controles.add(jb_guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 80, -1));

        jb_borrar.setText("Borrar");
        jb_borrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_borrarMouseClicked(evt);
            }
        });
        jp_controles.add(jb_borrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, 80, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jp_controlesmovimiento, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jp_datos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jp_controles, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jp_datos, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jp_controlesmovimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jp_controles, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void jb_cancelarActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void jb_anteriorActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void jb_siguienteMouseClicked(java.awt.event.MouseEvent evt) {                                          
        // TODO add your handling code here:
        try{             
            if(rs.isLast()==false) {                
                rs.next(); 
                this.jtf_id_producto.setText(rs.getString("id_producto"));                         
                this.jtf_nombre_producto.setText(rs.getString("nombre_producto"));             
                this.jtf_marca_producto.setText(rs.getString("marca_producto"));
                this.jtf_precio_producto.setText(rs.getString("precio_producto"));
                this.jtf_existencia_producto.setText(rs.getString("existencia_producto"));               
            }         
        }catch(Exception err) {             
            JOptionPane.showMessageDialog(null,"Error "+err.getMessage());         
        }  
    }                                         

    private void jb_anteriorMouseClicked(java.awt.event.MouseEvent evt) {                                         
        // TODO add your handling code here:
        try{             
            if(rs.isFirst()!=false) {                
            } else {
                rs.previous();
                this.jtf_id_producto.setText(rs.getString("id_producto"));             
                this.jtf_nombre_producto.setText(rs.getString("nombre_producto"));
                this.jtf_marca_producto.setText(rs.getString("marca_producto"));
                this.jtf_precio_producto.setText(rs.getString("precio_producto"));
                this.jtf_existencia_producto.setText(rs.getString("existencia_producto"));               
            }         
        }catch(Exception err) {             
            JOptionPane.showMessageDialog(null,"Error "+err.getMessage());         
        } 
    }                                        

    private void jb_nuevoMouseClicked(java.awt.event.MouseEvent evt) {                                      
        // TODO add your handling code here:
        anterior = 1;
        habilitarjtf(true);
        habilitarcontroles(false);
        jb_nuevo.setEnabled(false);
        jb_editar.setEnabled(false);
        jb_borrar.setEnabled(false);
        jb_guardar.setEnabled(true);
        jb_cancelar.setEnabled(true);
        limpiarjtf();
        
         
        
    }                                     

    private void jb_cancelarMouseClicked(java.awt.event.MouseEvent evt) {                                         
        // TODO add your handling code here:
        habilitarcontroles(true);
        habilitarjtf(false);
        jb_nuevo.setEnabled(true);
        jb_editar.setEnabled(true);
        jb_borrar.setEnabled(true);
        jb_guardar.setEnabled(false);
        jb_cancelar.setEnabled(false);
        this.Conectar();
    }                                        

    private void jb_editarMouseClicked(java.awt.event.MouseEvent evt) {                                       
        // TODO add your handling code here:
        anterior = 2;
        habilitarcontroles(false);
        jb_nuevo.setEnabled(false);
        jb_editar.setEnabled(false);
        jb_borrar.setEnabled(false);
        jb_guardar.setEnabled(true);
        jb_cancelar.setEnabled(true);
        habilitarjtf(true);
        
    }                                      

    private void jb_primeroMouseClicked(java.awt.event.MouseEvent evt) {                                        
        // TODO add your handling code here:
        try{             
            if(rs.isFirst() == true) {
            } else {
                rs.first();
                this.jtf_id_producto.setText(rs.getString("id_producto"));             
                this.jtf_nombre_producto.setText(rs.getString("nombre_producto"));
                this.jtf_marca_producto.setText(rs.getString("marca_producto"));
                this.jtf_precio_producto.setText(rs.getString("precio_producto"));
                this.jtf_existencia_producto.setText(rs.getString("existencia_producto"));                
            }         
        }catch(Exception err) {             
            JOptionPane.showMessageDialog(null,"Error "+err.getMessage());         
        } 
    }                                       

    private void jb_ultimoMouseClicked(java.awt.event.MouseEvent evt) {                                       
        // TODO add your handling code here:
         try{             
            if(rs.isLast() == true) {
            } else {
                rs.last();
                this.jtf_id_producto.setText(rs.getString("id_producto"));             
                this.jtf_nombre_producto.setText(rs.getString("nombre_producto"));
                this.jtf_marca_producto.setText(rs.getString("marca_producto"));
                this.jtf_precio_producto.setText(rs.getString("precio_producto"));
                this.jtf_existencia_producto.setText(rs.getString("existencia_producto"));                
            }         
        }catch(Exception err) {             
            JOptionPane.showMessageDialog(null,"Error "+err.getMessage());         
        } 
    }                                      

    private void jb_guardarMouseClicked(java.awt.event.MouseEvent evt) {                                        
        // TODO add your handling code here:
        if (anterior == 1){
            try{  
                String nombre = this.jtf_nombre_producto.getText();
                String marca=this.jtf_marca_producto.getText(); 
                float precio = Float.parseFloat(this.jtf_precio_producto.getText());
                Integer existencia = Integer.valueOf(this.jtf_existencia_producto.getText());

                st.executeUpdate("Insert into productos(nombre_producto,marca_producto,precio_producto,existencia_producto)"+" values ('"+ nombre +"','"+ marca +"','"+ precio +"','"+ existencia +"');"); 

                JOptionPane.showMessageDialog(null,"Producto guardado con exito...");
                this.Conectar();

                habilitarcontroles(true);
                habilitarjtf(false);
                jb_nuevo.setEnabled(true);
                jb_editar.setEnabled(true);
                jb_borrar.setEnabled(true);
                jb_guardar.setEnabled(false);
                jb_cancelar.setEnabled(false);

            } catch(SQLException err)         { 
                JOptionPane.showMessageDialog(this,"Error "+err.getMessage()); 
            } 
        }else if(anterior == 2){
            try{
                String nombre = this.jtf_nombre_producto.getText();
                String marca=this.jtf_marca_producto.getText(); 
                float precio = Float.parseFloat(this.jtf_precio_producto.getText());
                Integer existencia = Integer.valueOf(this.jtf_existencia_producto.getText());
                
                st.executeUpdate("UPDATE productos SET nombre_producto='"+ nombre +"',marca_producto='"+ marca +"',precio_producto='"+ precio +"',existencia_producto='"+ existencia+ "' WHERE id_producto="+this.jtf_id_producto.getText());
                
                JOptionPane.showMessageDialog(null,"Producto guardado con exito...");
                this.Conectar();

                habilitarcontroles(true);
                habilitarjtf(false);
                jb_nuevo.setEnabled(true);
                jb_editar.setEnabled(true);
                jb_borrar.setEnabled(true);
                jb_guardar.setEnabled(false);
                jb_cancelar.setEnabled(false);
                
            }catch(SQLException err){
                JOptionPane.showMessageDialog(this,"Error "+err.getMessage());
            }
        }
       
    }                                       

    private void jb_borrarMouseClicked(java.awt.event.MouseEvent evt) {                                       
        // TODO add your handling code here:
         try{ 
           st.executeUpdate("delete from productos where id_producto="+this.jtf_id_producto.getText());

            this.Conectar();
            habilitarcontroles(true);
            habilitarjtf(false);
            jb_nuevo.setEnabled(true);
            jb_editar.setEnabled(true);
            jb_borrar.setEnabled(true);
            jb_guardar.setEnabled(false);
            jb_cancelar.setEnabled(false);

        } catch(SQLException err){ 
            JOptionPane.showMessageDialog(null,"Error "+err.getMessage()); 
        } 
    }                                      

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jf_productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jf_productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jf_productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jf_productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jf_productos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton jb_anterior;
    private javax.swing.JButton jb_borrar;
    private javax.swing.JButton jb_cancelar;
    private javax.swing.JButton jb_editar;
    private javax.swing.JButton jb_guardar;
    private javax.swing.JButton jb_guardar1;
    private javax.swing.JButton jb_nuevo;
    private javax.swing.JButton jb_primero;
    private javax.swing.JButton jb_siguiente;
    private javax.swing.JButton jb_ultimo;
    private javax.swing.JPanel jp_controles;
    private javax.swing.JPanel jp_controlesmovimiento;
    private javax.swing.JPanel jp_datos;
    private javax.swing.JTextField jtf_existencia_producto;
    private javax.swing.JTextField jtf_id_producto;
    private javax.swing.JTextField jtf_marca_producto;
    private javax.swing.JTextField jtf_nombre_producto;
    private javax.swing.JTextField jtf_precio_producto;
    // End of variables declaration                   

    
}